# post de producto
GET     http://localhost:4000/products  
Content-Type: application/json
###
# post de producto
POST    http://localhost:4000/products 
Content-Type: application/json

{
    "id": 1,
    "nombre": "Smartphone X1",
    "marca": "TechBrand",
    "precio": 299.99,
    "stock": 50
  }

